export {
  useFaculties,
  useAllFaculties,
  useFaculty,
  useCreateFaculty,
  useUpdateFaculty,
  useDeleteFaculty,
  useDepartments,
  useAllDepartments,
  useDepartment,
  useCreateDepartment,
  useUpdateDepartment,
  useDeleteDepartment,
  useCourses,
  useAllCourses,
  useCourse,
  useCreateCourse,
  useUpdateCourse,
  useDeleteCourse,
  useCourseSections,
  useCourseSection,
  useCreateCourseSection,
  useUpdateCourseSection,
  useArchiveCourseSection,
  useDeleteCourseSection,
} from './useAcademic';

export {
  useStudents,
  useStudent,
  useCreateStudent,
  useUpdateStudent,
  useUpdateStudentStatus,
  useLecturers,
  useLecturer,
  useCreateLecturer,
  useUpdateLecturer,
  useUpdateLecturerStatus,
  useMyLecturerId,
} from './usePeople';

export {
  useMyEnrollments,
  useEnrollments,
  useCreateEnrollment,
  useApproveEnrollment,
  useRejectEnrollment,
  useDropEnrollment,
  useMyGrades,
  useMyTranscript,
  useSectionGrades,
  useUpdateGrade,
  useFinalizeGrade,
  useSectionAttendance,
  useCreateAttendance,
  useMyAttendance,
} from './useRecords';

export {
  useSectionWeeklySchedule,
  useMyWeeklySchedule,
  useCreateWeeklySlot,
  useUpdateWeeklySlot,
  useDeleteWeeklySlot,
  useSectionExamSchedule,
  useMyExamSchedule,
  useCreateExamSlot,
  useUpdateExamSlot,
  useDeleteExamSlot,
  useAnnouncements,
  useAnnouncement,
  useCreateAnnouncement,
  useUpdateAnnouncement,
  useDeleteAnnouncement,
  useCalendarEvents,
  useCreateCalendarEvent,
  useUpdateCalendarEvent,
  useDeleteCalendarEvent,
  useAdvisorAssignments,
  useAdvisees,
  useCreateAdvisorAssignment,
  useDeactivateAdvisorAssignment,
  useMe,
  useUpdateMe,
  useUploadPhoto,
  useUsers,
  useCreateUser,
  useUpdateUser,
  useUpdateUserStatus,
  useRoles,
  useUpdateRole,
  useLogs,
  useSectionMaterials,
  useUploadFile,
  useDeleteUpload,
} from './useSystem';

export { useDashboardStudent, useDashboardAcademician, useDashboardAdmin } from './useDashboard';
